services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "3001:80"
    restart: unless-stopped
    volumes:
      - ./dist:/app/dist
